name: deploy

on: workflow_dispatch

jobs:
  get-asteroids-and-deploy:
    runs-on: ubuntu-latest
    container: alexkennedy/solar-system:latest
    defaults:
      run:
        working-directory: /solar-system/
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
    steps:
      - name: Run get-asteroids-and-build.sh
        run: /solar-system/scripts/get-asteroids-and-build.sh
